version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: djangorestframework
    versions:
    - 3.11.1
